language: java

sudo: false
dist: trusty

before_install:
  - unset _JAVA_OPTIONS

install:
  - ./gradlew :agent:publishToMavenLocal
  - ./gradlew assemble

matrix:
  include:
    # OpenJDK - Java 8
    - jdk: openjdk8
    # OpenJDK - Java 11
    - jdk: oraclejdk11
    # OpenJDK - Java 13
    - jdk: openjdk-ea

script:
  - ./travis-test.sh

