language: java

sudo: false
dist: trusty

matrix:
  include:
    # OpenJDK - Java 8
    - jdk: openjdk8
    # OpenJDK - Java 11
    - jdk: oraclejdk11
    # OpenJDK - Java 13
    - jdk: openjdk-ea

script:
  - ./gradlew :agent:publishToMavenLocal
  - ./gradlew assemble
  - ./travis-test.sh

